pds_home_homepage:
    path:     /
    defaults: { _controller: PDSHomeBundle:Default:index }
    
pds_account_update:
    path:     /compte/update
    defaults: { _controller: PDSHomeBundle:Default:update }

pds_home_inbox:
    path:     /messages
    defaults: { _controller: PDSHomeBundle:Default:inbox }

pds_home_inboxpage:
    path:     /messages/{page}
    defaults: { _controller: PDSHomeBundle:Default:inboxpage }
    requirements:
        page:   \d

pds_home_changeAvatar:
    path:     /changer-d-avatar
    defaults: { _controller: PDSHomeBundle:Default:changeAvatar }

pds_home_sendMessageTo:
    path:     /messages/{id}/nouveau
    defaults: { _controller: PDSHomeBundle:Default:sendMessageTo }
    requirements:
        id:   \d