pds_home_homepage:
    path:     /
    defaults: { _controller: PDSHomeBundle:Default:index }
    
pds_account_update:
    path:     /compte/update
    defaults: { _controller: PDSHomeBundle:Default:update }

pds_home_inbox:
    path:     /messages
    defaults: { _controller: PDSHomeBundle:Default:inbox }
    
    
    
    
pds_friends_homepage:
    path:     /amis
    defaults: { _controller: PDSHomeBundle:Default:inbox }
    
pds_home_changeAvatar:
    path:     /changer-d-avatar
    defaults: { _controller: PDSHomeBundle:Default:changeAvatar }