services:
    pds_user.login.listener:
        class: PDS\UserBundle\Login\LoginListener
        arguments: ["@router", "@event_dispatcher"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }