
        main_login:
            pattern:   ^/(login|register|resetting|logout)
            anonymous: true
            form_login:
                login_path: 'fos_user_security_login'
                use_forward: false
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false
            logout:
                path: 'fos_user_security_logout'
        main:
            pattern: ^/
            anonymous: false
            provider: main
            form_login:
                check_path: 'fos_user_security_check'
            logout:
                path: 'fos_user_security_logout'
                target: 'fos_user_security_login'
            remember_me:
                key: "%secret%"
